### ISSUE TITLE
let's deprecate scala.util.parsing.json

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parser-combinators#99]
it was never intended for production use; it's really more of a code sample demonstrating how to use parser combinators. unfortunately, over the years a huge volume of Scala newcomers have slid down the slippery maw of this gaudy, carnivorous plant and dissolved.

probably it would have been derpecated (typo, but I'll let it stand) years ago, but we have historically been reluctant to deprecate things when we couldn't clearly provide and recommend a specific replacement. but that isn't going to happen anytime soon. _perhaps_ eventually there will be a JSON parser in the Scala Platform, but there isn't even a proposal for that yet. (@mdedetrich's well-known Scala Platform proposal is about JSON ASTs, not a parser.)

so let's go ahead and just deprecate the scala.util.parsing.json package in its entirety, in a release which would be bundled with some Scala 2.12.x release.

by the time Scala 2.13 rolls around, either we will no longer be bundling this library at all, or if for some reason we still are, we can bundle a version that does not include the JSON parsers.

the only real difficulty that I see is crafting a suitable deprecation message. is there something better we can tell people, or do we just have to say something like "seek third party alternatives"?

**Comment by dwijnand** [comment]
Maybe we can use the Scaladex? "Seek alternatives on index.scala-lang.org"?

**Comment by SethTisue** [comment]
so, this seems popular. would anyone like volunteer to actually do the deprecation and submit a PR?

**Comment by gourlaysama** [comment]
Fixed in #103 :)

**Comment by SethTisue** [comment]
yay!

@gourlaysama were you thinking of rolling a release anytime soon? this could still get into Scala 2.12.2. (though if that doesn't happen, it's no tragedy)

**Comment by gourlaysama** [comment]
@SethTisue sure. I'll tag 1.0.6 after #106 is in :)

**Comment by SethTisue** [comment]
@gourlaysama ping... let me know if there's anything I (/ the community) could help with?

**Comment by SethTisue** [comment]
my other motivation for hoping for a release in a not-too-distant future is so I can finish off https://github.com/scala/scala-parser-combinators/pull/97 for Scala 2.13.0-M1

**Comment by SethTisue** [comment]
Another newcomer swallowed: https://users.scala-lang.org/t/find-value-in-nested-map-parsed-from-json/505/6

**Comment by SethTisue** [comment]
@gourlaysama we'll be building 2.12.3 a few weeks from now. if you've been thinking about doing a release, this would be an opportune time

**Comment by SethTisue** [comment]
for anyone visiting this ticket: the deprecation is in 1.0.6, which will ship with Scala 2.12.3
